# Welcome to Jekyll!

# Website settings
title: "Mourad Mars"
description: "Personal website of Mourad Mars"
keywords: "Mourad, Mars, Natural Language Processing, Machine Learning, Artificial Intelligence"
baseurl: "/"
url: "http://mouradmars.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Mourad'
  first_name: 'Mars'
  last_name: 'Mourad'
  email: 'mourad.mars@univ-grenoble-alpes.fr'
  linkedin_username: 'https://www.linkedin.com/in/mouradmars'
  github_username: 'mouradmars'
  scholar_username: 'https://scholar.google.com/citations?user=f57ZIvUAAAAJ&hl=en'
  head_img: 'static/img/landing/picture.png'
  desc: 'I am a researcher focusing on natural language processing, and machine learning. I strive for open source and open data.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: 'publications'
    
  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
    
    - id: 'publications'
    i18n: 'nav.publications'
    name: 'Teaching'
    tpl: 'Teaching.html'
    css: 'publications'
    
  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'fr'
    flag: 'static/img/flags/France.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

